/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

package org.dexpace.kuri.idna

/**
 * Inputs that [Idna.domainToAscii] still fails the WPT IDNA corpora (IdnaTestV2 + toascii) on,
 * tracked so [IdnaConformanceTest] ratchets: the live failing set must equal this set exactly,
 * so closing a gap (or a regression) breaks the build until this baseline is regenerated.
 *
 * Every entry is a check the URL host layer applies on top of UTS-46 ToASCII, not inside it:
 * a forbidden host code point (e.g. a C0 control, U+00A0, the U+2A74 expansion) or the
 * empty domain. None reflect a Punycode/mapping/NFC/ContextJ/Bidi or re-validation defect in
 * [Idna.domainToAscii] itself.
 *
 * GENERATED by ./gradlew generateIdnaConformanceFixture from the WPT corpora; do not edit by hand.
 */
private object IdnaKnownFailureData {
    fun all(): Set<String> =
        setOf(
            "",
            "\u001flookout.net",
            "www.lookout.net\u2a7480",
            "www\u00a0.lookout.net",
        )
}

/** Tracked baseline of currently-failing conformance inputs (see [IdnaKnownFailureData]). */
internal val IDNA_KNOWN_FAILURES: Set<String> = IdnaKnownFailureData.all()
