/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

package org.dexpace.kuri.idna

/**
 * Inputs that [Idna.domainToAscii] still fails the WPT IDNA corpora (IdnaTestV2 + toascii) on,
 * tracked so [IdnaConformanceTest] ratchets: the live failing set must equal this set exactly,
 * so closing a gap (or a regression) breaks the build until this baseline is regenerated.
 *
 * Every entry is a UTS-46 criterion this `Url`-profile run does not apply (CheckBidi,
 * decoded-A-label re-validation, host-layer forbidden code points, empty-domain length) or a
 * corpus/Unicode-version corner -- none reflect a Punycode/mapping/NFC output defect.
 *
 * GENERATED by ./gradlew generateIdnaConformanceFixture from the WPT corpora; do not edit by hand.
 */
private object IdnaKnownFailureData {
    fun all(): Set<String> =
        setOf(
            "",
            "\u001flookout.net",
            "1\u0627",
            "a\u0301\u05d0",
            "a\u05d0",
            "a\u05d0\u0301",
            "a\u05d0\u05d1",
            "a\u0627",
            "a\u0661",
            "look\u05beout.net",
            "www.lookout.net\u2a7480",
            "www\u00a0.lookout.net",
            "xn--",
            "xn---",
            "xn--20-9802c.xn--0w5a.xn--1-eg4e.",
            "xn--9-i0j5967eg3qz.ss",
            "xn--ASCII-",
            "xn--a-yoc",
            "xn--u-ccb",
            "xn--unicode-.org",
            "xn--xn---epa",
            "xn--xn--a--gua.pt",
            "\u064aa",
            "\u0660",
            "\u0660\u0627",
            "\ud88a\udd3120.\u97f3.\ua8661.",
            "\ud88a\udf9a9\ua369\u17d3.SS",
            "\ud88a\udf9a9\ua369\u17d3.ss",
        )
}

/** Tracked baseline of currently-failing conformance inputs (see [IdnaKnownFailureData]). */
internal val IDNA_KNOWN_FAILURES: Set<String> = IdnaKnownFailureData.all()
