/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

package org.dexpace.kuri.idna

/**
 * The permanent host-layer residual: WPT IDNA corpus inputs (IdnaTestV2 + toascii) that the WHATWG
 * host parser rejects on top of UTS-46 ToASCII, and that [Idna.domainToAscii] (a pure ToASCII
 * engine) therefore accepts. Each is a forbidden host code point (e.g. a C0 control, U+00A0, the
 * U+2A74 expansion) or the empty domain; none reflect a Punycode/mapping/NFC/ContextJ/Bidi or
 * re-validation defect in [Idna.domainToAscii] itself. The set is out of scope for this engine
 * harness and stable by design, changing only with the corpus or with host-layer ownership.
 *
 * [IdnaConformanceTest] ratchets against it (a new regression, or drift from the live failing set,
 * breaks the build until this baseline is regenerated) and asserts the scope explicitly: every
 * entry is accepted by [Idna.domainToAscii] yet rejected by the URL host layer.
 *
 * GENERATED by ./gradlew generateIdnaConformanceFixture from the WPT corpora; do not edit by hand.
 */
private object IdnaKnownFailureData {
    fun all(): Set<String> =
        setOf(
            "",
            "\u001flookout.net",
            "www.lookout.net\u2a7480",
            "www\u00a0.lookout.net",
        )
}

/** Tracked baseline of currently-failing conformance inputs (see [IdnaKnownFailureData]). */
internal val IDNA_KNOWN_FAILURES: Set<String> = IdnaKnownFailureData.all()
