#!/usr/bin/env python3
# Copyright (c) 2026 dexpace and Omar Aljarrah
# SPDX-License-Identifier: MIT
r"""Generate kuri's NFC conformance test fixture from Unicode's NormalizationTest.txt.

Offline build tool. It parses the official Unicode 16.0 conformance corpus:

    .claude/references/unicode-16.0/NormalizationTest.txt

(columns: source;NFC;NFD;NFKC;NFKD, each a space-separated list of hex code
points) and emits a multiplatform-safe Kotlin test data file:

    kuri/src/commonTest/kotlin/org/dexpace/kuri/idna/NfcTestData.kt

Only the `source` and `NFC` columns are kept (this fixture validates NFC). The
`@PartN` headers and `#` comments are skipped. Cases are chunked into small
builder functions so no single method approaches the 64 KB JVM method limit,
and string literals are pure ASCII (non-ASCII scalars escaped as `\uXXXX`,
supplementary scalars as a surrogate pair of escapes).
"""

import os
import sys

RADIX_HEX = 16
SOURCE_COLUMN = 0
NFC_COLUMN = 1

# Pure-ASCII Kotlin string-literal escaping bounds.
SAFE_LITERAL_MIN = 0x20
SAFE_LITERAL_MAX = 0x7E
SPECIAL_LITERAL_CHARS = {'"', "\\", "$"}
BMP_MAX = 0xFFFF
SURROGATE_BASE = 0x10000
HIGH_SURROGATE_MIN = 0xD800
LOW_SURROGATE_MIN = 0xDC00
SURROGATE_HIGH_SHIFT = 10
SURROGATE_LOW_MASK = 0x3FF

# Cases per generated builder function (well under the 64 KB JVM method limit).
CHUNK = 400

# The single-line `NfcCase("s", "n"),` form is preferred; cases whose escaped form would
# exceed this column limit are emitted across multiple lines instead.
MAX_LINE = 120

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SOURCE_TXT = os.path.join(
    REPO_ROOT, ".claude", "references", "unicode-16.0", "NormalizationTest.txt",
)
OUTPUT_KT = os.path.join(
    REPO_ROOT, "kuri", "src", "commonTest", "kotlin", "org", "dexpace",
    "kuri", "idna", "NfcTestData.kt",
)

LICENSE_HEADER = (
    "/*\n"
    " * Copyright (c) 2026 dexpace and Omar Aljarrah\n"
    " * SPDX-License-Identifier: MIT\n"
    " */\n"
)


def scalars_to_string(field):
    return "".join(chr(int(token, RADIX_HEX)) for token in field.split())


def load_cases(path):
    """Parse (source, nfc) string pairs, skipping comments and @Part headers."""
    cases = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            body = line.split("#", 1)[0].strip()
            if not body or body.startswith("@"):
                continue
            columns = body.split(";")
            source = scalars_to_string(columns[SOURCE_COLUMN])
            nfc = scalars_to_string(columns[NFC_COLUMN])
            cases.append((source, nfc))
    return cases


def escape_char(ch):
    """Escape a single character into a pure-ASCII Kotlin string literal fragment."""
    code = ord(ch)
    if SAFE_LITERAL_MIN <= code <= SAFE_LITERAL_MAX and ch not in SPECIAL_LITERAL_CHARS:
        return ch
    if code <= BMP_MAX:
        return "\\u%04x" % code
    offset = code - SURROGATE_BASE
    high = HIGH_SURROGATE_MIN + (offset >> SURROGATE_HIGH_SHIFT)
    low = LOW_SURROGATE_MIN + (offset & SURROGATE_LOW_MASK)
    return "\\u%04x\\u%04x" % (high, low)


def escape_string(value):
    return "".join(escape_char(ch) for ch in value)


def chunked(items, size):
    for start in range(0, len(items), size):
        yield items[start:start + size]


def case_lines(source, nfc):
    """Render one NfcCase, wrapping to multiple lines when a single line would exceed MAX_LINE."""
    source_lit = escape_string(source)
    nfc_lit = escape_string(nfc)
    single = '            NfcCase("%s", "%s"),' % (source_lit, nfc_lit)
    if len(single) <= MAX_LINE:
        return [single]
    return [
        "            NfcCase(",
        '                "%s",' % source_lit,
        '                "%s",' % nfc_lit,
        "            ),",
    ]


def render_kotlin(cases):
    parts = list(chunked(cases, CHUNK))
    lines = [
        LICENSE_HEADER.rstrip("\n"),
        "",
        "// Generated bulk data, not hand-written logic: the chunked builders intentionally exceed",
        "// detekt's method/class-size heuristics to stay within the 64 KB JVM method limit.",
        '@file:Suppress("LongMethod", "LargeClass", "MatchingDeclarationName")',
        "",
        "package org.dexpace.kuri.idna",
        "",
        "/** One Unicode NormalizationTest.txt case: [nfc] is the required NFC form of [source]. */",
        "internal data class NfcCase(",
        "    val source: String,",
        "    val nfc: String,",
        ")",
        "",
        "// Generated by tools/idna/generate_nfc_test_fixture.py from NormalizationTest.txt.",
        "private object NfcCaseData {",
    ]
    sum_expr = " +\n            ".join("part%d()" % i for i in range(len(parts)))
    lines.append("    fun all(): List<NfcCase> =")
    lines.append("        " + sum_expr)
    for index, part in enumerate(parts):
        lines.append("")
        lines.append("    private fun part%d(): List<NfcCase> =" % index)
        lines.append("        listOf(")
        for source, nfc in part:
            lines.extend(case_lines(source, nfc))
        lines.append("        )")
    lines.append("}")
    lines.append("")
    lines.append("/** Every NormalizationTest.txt case as `(source, NFC)` (see [NfcCaseData]). */")
    lines.append("internal val NFC_CASES: List<NfcCase> = NfcCaseData.all()")
    lines.append("")
    return "\n".join(lines)


def main():
    cases = load_cases(SOURCE_TXT)
    with open(OUTPUT_KT, "w", encoding="utf-8") as handle:
        handle.write(render_kotlin(cases))
    print("cases  : %d" % len(cases))
    print("output : %s" % OUTPUT_KT)


if __name__ == "__main__":
    sys.exit(main())
