/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

// Generated bulk data, not hand-written logic: the chunked builders intentionally exceed
// detekt's method/class-size heuristics to stay within the 64 KB JVM method limit.
@file:Suppress("LongMethod", "LargeClass", "MatchingDeclarationName")

package org.dexpace.kuri.percent

/**
 * One WPT `percent-encoding.json` case carrying a `utf-8` expectation (the only charset in
 * scope for kuri). Percent-encoding [input] under the C0-control set over UTF-8 bytes must
 * equal [utf8].
 */
internal data class PercentEncodingCase(
    val input: String,
    val utf8: String,
)

// Generated by ./gradlew generatePercentEncodingTestData from the WPT percent-encoding corpus.
// Chunked into small builders so no single method exceeds the 64 KB JVM limit.
private object PercentEncodingCaseData {
    fun all(): List<PercentEncodingCase> = part0()

    private fun part0(): List<PercentEncodingCase> =
        listOf(
            PercentEncodingCase(
                input = "\u2020",
                utf8 = "%E2%80%A0",
            ),
            PercentEncodingCase(
                input = "\u000eA",
                utf8 = "%0EA",
            ),
            PercentEncodingCase(
                input = "\u203e\\",
                utf8 = "%E2%80%BE\\",
            ),
            PercentEncodingCase(
                input = "\ue5e5",
                utf8 = "%EE%97%A5",
            ),
            PercentEncodingCase(
                input = "\u2212",
                utf8 = "%E2%88%92",
            ),
            PercentEncodingCase(
                input = "\u00a2",
                utf8 = "%C2%A2",
            ),
            PercentEncodingCase(
                input = "\u00e1|",
                utf8 = "%C3%A1|",
            ),
        )
}

/** Every WPT `percent-encoding.json` case carrying a `utf-8` expectation. */
internal val PERCENT_ENCODING_TEST_CASES: List<PercentEncodingCase> = PercentEncodingCaseData.all()
