/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

// Generated bulk data, not hand-written logic: the chunked builders intentionally exceed
// detekt's method/class-size heuristics to stay within the 64 KB JVM method limit.
@file:Suppress("LongMethod", "LargeClass", "MatchingDeclarationName")

package org.dexpace.kuri.parser

/**
 * One WPT `setters_tests.json` case. Assigning [newValue] through the [component] setter on
 * the URL parsed from [href] must leave every getter named in [expected] (keyed by getter name,
 * e.g. `href`, `protocol`, `hostname`) equal to its mapped string; [expected] is unordered.
 */
internal data class SetterCase(
    val component: String,
    val href: String,
    val newValue: String,
    val expected: Map<String, String>,
)

// Generated by ./gradlew generateSetterTestData from the WPT setters_tests corpus.
// Chunked into small builders so no single method exceeds the 64 KB JVM limit.
private object SetterCaseData {
    fun all(): List<SetterCase> =
        part0() +
            part1() +
            part2() +
            part3() +
            part4()

    private fun part0(): List<SetterCase> =
        listOf(
            SetterCase(
                component = "hash",
                href = "https://example.net",
                newValue = "main",
                expected = mapOf("hash" to "#main", "href" to "https://example.net/#main"),
            ),
            SetterCase(
                component = "hash",
                href = "https://example.net#nav",
                newValue = "main",
                expected = mapOf("hash" to "#main", "href" to "https://example.net/#main"),
            ),
            SetterCase(
                component = "hash",
                href = "https://example.net?lang=en-US",
                newValue = "##nav",
                expected = mapOf("hash" to "##nav", "href" to "https://example.net/?lang=en-US##nav"),
            ),
            SetterCase(
                component = "hash",
                href = "https://example.net?lang=en-US#nav",
                newValue = "#main",
                expected = mapOf("hash" to "#main", "href" to "https://example.net/?lang=en-US#main"),
            ),
            SetterCase(
                component = "hash",
                href = "https://example.net?lang=en-US#nav",
                newValue = "#",
                expected = mapOf("hash" to "", "href" to "https://example.net/?lang=en-US#"),
            ),
            SetterCase(
                component = "hash",
                href = "https://example.net?lang=en-US#nav",
                newValue = "",
                expected = mapOf("hash" to "", "href" to "https://example.net/?lang=en-US"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "#foo bar",
                expected = mapOf("hash" to "#foo%20bar", "href" to "http://example.net/#foo%20bar"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "#foo\"bar",
                expected = mapOf("hash" to "#foo%22bar", "href" to "http://example.net/#foo%22bar"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "#foo<bar",
                expected = mapOf("hash" to "#foo%3Cbar", "href" to "http://example.net/#foo%3Cbar"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "#foo>bar",
                expected = mapOf("hash" to "#foo%3Ebar", "href" to "http://example.net/#foo%3Ebar"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "#foo`bar",
                expected = mapOf("hash" to "#foo%60bar", "href" to "http://example.net/#foo%60bar"),
            ),
            SetterCase(
                component = "hash",
                href = "a:/",
                newValue =
                    "\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "hash" to
                            "#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%80%C2%81%C3%89%C3%A9",
                        "href" to
                            "a:/#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%80%C2%81%C3%89%C3" +
                            "%A9",
                    ),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "a\u0000b",
                expected = mapOf("hash" to "#a%00b", "href" to "http://example.net/#a%00b"),
            ),
            SetterCase(
                component = "hash",
                href = "non-spec:/",
                newValue = "a\u0000b",
                expected = mapOf("hash" to "#a%00b", "href" to "non-spec:/#a%00b"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "%c3%89t\u00e9",
                expected = mapOf("hash" to "#%c3%89t%C3%A9", "href" to "http://example.net/#%c3%89t%C3%A9"),
            ),
            SetterCase(
                component = "hash",
                href = "javascript:alert(1)",
                newValue = "castle",
                expected = mapOf("hash" to "#castle", "href" to "javascript:alert(1)#castle"),
            ),
            SetterCase(
                component = "hash",
                href =
                    "data:space                                                                                  " +
                        "                                                #fragment",
                newValue = "",
                expected =
                    mapOf(
                        "hash" to "",
                        "href" to
                            "data:space                                                                              " +
                            "                                                   %20",
                        "pathname" to
                            "space                                                                                   " +
                            "                                              %20",
                    ),
            ),
            SetterCase(
                component = "hash",
                href = "sc:space    #fragment",
                newValue = "",
                expected = mapOf("hash" to "", "href" to "sc:space   %20", "pathname" to "space   %20"),
            ),
            SetterCase(
                component = "hash",
                href = "data:space  ?query#fragment",
                newValue = "",
                expected = mapOf("hash" to "", "href" to "data:space %20?query"),
            ),
            SetterCase(
                component = "hash",
                href = "sc:space  ?query#fragment",
                newValue = "",
                expected = mapOf("hash" to "", "href" to "sc:space %20?query"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = " ",
                expected = mapOf("hash" to "#%20", "href" to "http://example.net/#%20"),
            ),
            SetterCase(
                component = "hash",
                href = "http://example.net",
                newValue = "\u0000",
                expected = mapOf("hash" to "#%00", "href" to "http://example.net/#%00"),
            ),
            SetterCase(
                component = "hash",
                href = "data:text/plain,test",
                newValue = "#<foo> <bar>",
                expected =
                    mapOf(
                        "hash" to "#%3Cfoo%3E%20%3Cbar%3E",
                        "href" to "data:text/plain,test#%3Cfoo%3E%20%3Cbar%3E",
                    ),
            ),
            SetterCase(
                component = "hash",
                href = "about:blank",
                newValue = "#<foo> <bar>",
                expected = mapOf("hash" to "#%3Cfoo%3E%20%3Cbar%3E", "href" to "about:blank#%3Cfoo%3E%20%3Cbar%3E"),
            ),
            SetterCase(
                component = "hash",
                href = "data:text/plain,test",
                newValue =
                    "#\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "hash" to
                            "#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%80%C2%81%C3%89%C3%A9",
                        "href" to
                            "data:text/plain,test#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%" +
                            "80%C2%81%C3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "hash",
                href = "about:blank",
                newValue =
                    "#\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "hash" to
                            "#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%80%C2%81%C3%89%C3%A9",
                        "href" to
                            "about:blank#%00%01%1F%20!%22#\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_%60az{|}~%7F%C2%80%C2%81%" +
                            "C3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "\u0000",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "\u0009",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "\u000a",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "\u000d",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = " ",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "#",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "/",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "?",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "@",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "host",
                href = "sc://x/",
                newValue = "\u00df",
                expected = mapOf("host" to "%C3%9F", "hostname" to "%C3%9F", "href" to "sc://%C3%9F/"),
            ),
            SetterCase(
                component = "host",
                href = "https://x/",
                newValue = "\u00df",
                expected = mapOf("host" to "xn--zca", "hostname" to "xn--zca", "href" to "https://xn--zca/"),
            ),
            SetterCase(
                component = "host",
                href = "mailto:me@example.net",
                newValue = "example.com",
                expected = mapOf("host" to "", "href" to "mailto:me@example.net"),
            ),
            SetterCase(
                component = "host",
                href = "data:text/plain,Stuff",
                newValue = "example.net",
                expected = mapOf("host" to "", "href" to "data:text/plain,Stuff"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "example.com:8080",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080",
                newValue = "example.com",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080",
                newValue = "example.com:",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "",
                expected = mapOf("host" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "view-source+http://example.net/foo",
                newValue = "",
                expected = mapOf("host" to "", "href" to "view-source+http:///foo"),
            ),
            SetterCase(
                component = "host",
                href = "a:/foo",
                newValue = "example.net",
                expected = mapOf("host" to "example.net", "href" to "a://example.net/foo"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "0x7F000001:8080",
                expected =
                    mapOf(
                        "host" to "127.0.0.1:8080",
                        "hostname" to "127.0.0.1",
                        "href" to "http://127.0.0.1:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "[::0:01]:2",
                expected =
                    mapOf(
                        "host" to "[::1]:2",
                        "hostname" to "[::1]",
                        "href" to "http://[::1]:2/",
                        "port" to "2",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "[2001:db8::2]:4002",
                expected =
                    mapOf(
                        "host" to "[2001:db8::2]:4002",
                        "hostname" to "[2001:db8::2]",
                        "href" to "http://[2001:db8::2]:4002/",
                        "port" to "4002",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net",
                newValue = "example.com:80",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://example.net",
                newValue = "example.com:443",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://example.net",
                newValue = "example.com:80",
                expected =
                    mapOf(
                        "host" to "example.com:80",
                        "hostname" to "example.com",
                        "href" to "https://example.com:80/",
                        "port" to "80",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080",
                newValue = "example.com:80",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com/stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080/stuff",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com?stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com?stuff:8080",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080?stuff",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com#stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080#stuff",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com\\stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
        )

    private fun part1(): List<SetterCase> =
        listOf(
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080\\stuff",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "view-source+http://example.net/path",
                newValue = "example.com\\stuff",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "view-source+http://example.net/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "view-source+http://example.net/path",
                newValue = "example.com:8080stuff2",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "view-source+http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080stuff2",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:8080+2",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080",
                newValue = "example.com:invalid",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080/test",
                newValue = "[::1]:invalid",
                expected =
                    mapOf(
                        "host" to "[::1]:8080",
                        "hostname" to "[::1]",
                        "href" to "http://[::1]:8080/test",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net:8080/test",
                newValue = "[::1]",
                expected =
                    mapOf(
                        "host" to "[::1]:8080",
                        "hostname" to "[::1]",
                        "href" to "http://[::1]:8080/test",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:65535",
                expected =
                    mapOf(
                        "host" to "example.com:65535",
                        "hostname" to "example.com",
                        "href" to "http://example.com:65535/path",
                        "port" to "65535",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/path",
                newValue = "example.com:65536",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/",
                newValue = "[google.com]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/",
                newValue = "[::1.2.3.4x]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/",
                newValue = "[::1.2.3.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/",
                newValue = "[::1.2.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.net/",
                newValue = "[::1.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "host",
                href = "file://y/",
                newValue = "x:123",
                expected = mapOf("host" to "y", "hostname" to "y", "href" to "file://y/", "port" to ""),
            ),
            SetterCase(
                component = "host",
                href = "file://y/",
                newValue = "loc%41lhost",
                expected = mapOf("host" to "", "hostname" to "", "href" to "file:///", "port" to ""),
            ),
            SetterCase(
                component = "host",
                href = "file://hi/x",
                newValue = "",
                expected = mapOf("host" to "", "hostname" to "", "href" to "file:///x", "port" to ""),
            ),
            SetterCase(
                component = "host",
                href = "sc://test@test/",
                newValue = "",
                expected =
                    mapOf(
                        "host" to "test",
                        "hostname" to "test",
                        "href" to "sc://test@test/",
                        "username" to "test",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "sc://test:12/",
                newValue = "",
                expected = mapOf("host" to "test:12", "hostname" to "test", "href" to "sc://test:12/", "port" to "12"),
            ),
            SetterCase(
                component = "host",
                href = "http://example.com/",
                newValue = "///bad.com",
                expected = mapOf("host" to "example.com", "hostname" to "example.com", "href" to "http://example.com/"),
            ),
            SetterCase(
                component = "host",
                href = "sc://example.com/",
                newValue = "///bad.com",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "host",
                href = "https://example.com/",
                newValue = "a%C2%ADb",
                expected = mapOf("host" to "ab", "hostname" to "ab", "href" to "https://ab/"),
            ),
            SetterCase(
                component = "host",
                href = "https://example.com/",
                newValue = "\u00ad",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://example.com/",
                newValue = "%C2%AD",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://example.com/",
                newValue = "xn--",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "*",
                expected = mapOf("host" to "*", "hostname" to "*", "href" to "https://*/"),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "x@x",
                expected =
                    mapOf(
                        "host" to "test.invalid",
                        "hostname" to "test.invalid",
                        "href" to "https://test.invalid/",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "foo\u0009\u000d\u000abar",
                expected = mapOf("host" to "foobar", "hostname" to "foobar", "href" to "https://foobar/"),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "><",
                expected =
                    mapOf(
                        "host" to "test.invalid",
                        "hostname" to "test.invalid",
                        "href" to "https://test.invalid/",
                    ),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "test/@aaa",
                expected = mapOf("host" to "test", "hostname" to "test", "href" to "https://test/"),
            ),
            SetterCase(
                component = "host",
                href = "https://test.invalid/",
                newValue = "test/:aaa",
                expected = mapOf("host" to "test", "hostname" to "test", "href" to "https://test/"),
            ),
            SetterCase(
                component = "host",
                href = "foo://path/to",
                newValue = ":80",
                expected = mapOf("host" to "path", "href" to "foo://path/to", "port" to ""),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "\u0000",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "\u0009",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "\u000a",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "\u000d",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = " ",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "#",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "/",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "?",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://x/",
                newValue = "@",
                expected = mapOf("host" to "x", "hostname" to "x", "href" to "sc://x/"),
            ),
            SetterCase(
                component = "hostname",
                href = "mailto:me@example.net",
                newValue = "example.com",
                expected = mapOf("host" to "", "href" to "mailto:me@example.net"),
            ),
            SetterCase(
                component = "hostname",
                href = "data:text/plain,Stuff",
                newValue = "example.net",
                expected = mapOf("host" to "", "href" to "data:text/plain,Stuff"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net:8080",
                newValue = "example.com",
                expected =
                    mapOf(
                        "host" to "example.com:8080",
                        "hostname" to "example.com",
                        "href" to "http://example.com:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net",
                newValue = "",
                expected = mapOf("host" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "hostname",
                href = "view-source+http://example.net/foo",
                newValue = "",
                expected = mapOf("host" to "", "href" to "view-source+http:///foo"),
            ),
            SetterCase(
                component = "hostname",
                href = "a:/foo",
                newValue = "example.net",
                expected = mapOf("host" to "example.net", "href" to "a://example.net/foo"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net:8080",
                newValue = "0x7F000001",
                expected =
                    mapOf(
                        "host" to "127.0.0.1:8080",
                        "hostname" to "127.0.0.1",
                        "href" to "http://127.0.0.1:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net",
                newValue = "[::0:01]",
                expected = mapOf("host" to "[::1]", "hostname" to "[::1]", "href" to "http://[::1]/", "port" to ""),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/path",
                newValue = "example.com:8080",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "http://example.net/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net:8080/path",
                newValue = "example.com:",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/path",
                newValue = "example.com/stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/path",
                newValue = "example.com?stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/path",
                newValue = "example.com#stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/path",
                newValue = "example.com\\stuff",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "http://example.com/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "view-source+http://example.net/path",
                newValue = "example.com\\stuff",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "view-source+http://example.net/path",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/",
                newValue = "[google.com]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/",
                newValue = "[::1.2.3.4x]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/",
                newValue = "[::1.2.3.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
        )

    private fun part2(): List<SetterCase> =
        listOf(
            SetterCase(
                component = "hostname",
                href = "http://example.net/",
                newValue = "[::1.2.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.net/",
                newValue = "[::1.]",
                expected = mapOf("host" to "example.net", "hostname" to "example.net", "href" to "http://example.net/"),
            ),
            SetterCase(
                component = "hostname",
                href = "file://y/",
                newValue = "x:123",
                expected = mapOf("host" to "y", "hostname" to "y", "href" to "file://y/", "port" to ""),
            ),
            SetterCase(
                component = "hostname",
                href = "file://y/",
                newValue = "loc%41lhost",
                expected = mapOf("host" to "", "hostname" to "", "href" to "file:///", "port" to ""),
            ),
            SetterCase(
                component = "hostname",
                href = "file://hi/x",
                newValue = "",
                expected = mapOf("host" to "", "hostname" to "", "href" to "file:///x", "port" to ""),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://test@test/",
                newValue = "",
                expected =
                    mapOf(
                        "host" to "test",
                        "hostname" to "test",
                        "href" to "sc://test@test/",
                        "username" to "test",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://test:12/",
                newValue = "",
                expected = mapOf("host" to "test:12", "hostname" to "test", "href" to "sc://test:12/", "port" to "12"),
            ),
            SetterCase(
                component = "hostname",
                href = "non-spec:/.//p",
                newValue = "h",
                expected = mapOf("host" to "h", "hostname" to "h", "href" to "non-spec://h//p", "pathname" to "//p"),
            ),
            SetterCase(
                component = "hostname",
                href = "non-spec:/.//p",
                newValue = "",
                expected = mapOf("host" to "", "hostname" to "", "href" to "non-spec:////p", "pathname" to "//p"),
            ),
            SetterCase(
                component = "hostname",
                href = "http://example.com/",
                newValue = "///bad.com",
                expected = mapOf("host" to "example.com", "hostname" to "example.com", "href" to "http://example.com/"),
            ),
            SetterCase(
                component = "hostname",
                href = "sc://example.com/",
                newValue = "///bad.com",
                expected = mapOf("host" to "", "hostname" to "", "href" to "sc:///"),
            ),
            SetterCase(
                component = "hostname",
                href = "https://example.com/",
                newValue = "a%C2%ADb",
                expected = mapOf("host" to "ab", "hostname" to "ab", "href" to "https://ab/"),
            ),
            SetterCase(
                component = "hostname",
                href = "https://example.com/",
                newValue = "\u00ad",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "https://example.com/",
                newValue = "%C2%AD",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "https://example.com/",
                newValue = "xn--",
                expected =
                    mapOf(
                        "host" to "example.com",
                        "hostname" to "example.com",
                        "href" to "https://example.com/",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "*",
                expected = mapOf("host" to "*", "hostname" to "*", "href" to "https://*/"),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "x@x",
                expected =
                    mapOf(
                        "host" to "test.invalid",
                        "hostname" to "test.invalid",
                        "href" to "https://test.invalid/",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "foo\u0009\u000d\u000abar",
                expected = mapOf("host" to "foobar", "hostname" to "foobar", "href" to "https://foobar/"),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "><",
                expected =
                    mapOf(
                        "host" to "test.invalid",
                        "hostname" to "test.invalid",
                        "href" to "https://test.invalid/",
                    ),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "test/@aaa",
                expected = mapOf("host" to "test", "hostname" to "test", "href" to "https://test/"),
            ),
            SetterCase(
                component = "hostname",
                href = "https://test.invalid/",
                newValue = "test/:aaa",
                expected = mapOf("host" to "test", "hostname" to "test", "href" to "https://test/"),
            ),
            SetterCase(
                component = "href",
                href = "file:///var/log/system.log",
                newValue = "http://0300.168.0xF0",
                expected = mapOf("href" to "http://192.168.0.240/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "password",
                href = "file:///home/me/index.html",
                newValue = "secret",
                expected = mapOf("href" to "file:///home/me/index.html", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "unix:/run/foo.socket",
                newValue = "secret",
                expected = mapOf("href" to "unix:/run/foo.socket", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "mailto:me@example.net",
                newValue = "secret",
                expected = mapOf("href" to "mailto:me@example.net", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "http://example.net",
                newValue = "secret",
                expected = mapOf("href" to "http://:secret@example.net/", "password" to "secret"),
            ),
            SetterCase(
                component = "password",
                href = "http://me@example.net",
                newValue = "secret",
                expected = mapOf("href" to "http://me:secret@example.net/", "password" to "secret"),
            ),
            SetterCase(
                component = "password",
                href = "http://:secret@example.net",
                newValue = "",
                expected = mapOf("href" to "http://example.net/", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "http://me:secret@example.net",
                newValue = "",
                expected = mapOf("href" to "http://me@example.net/", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "http://example.net",
                newValue =
                    "\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "href" to
                            "http://:%00%01%09%0A%0D%1F%20!%22%23\$%&'()*+,-.%2F09%3A%3B%3C%3D%3E%3F%40AZ%5B%5C%5D%5E" +
                            "_%60az%7B%7C%7D~%7F%C2%80%C2%81%C3%89%C3%A9@example.net/",
                        "password" to
                            "%00%01%09%0A%0D%1F%20!%22%23\$%&'()*+,-.%2F09%3A%3B%3C%3D%3E%3F%40AZ%5B%5C%5D%5E_%60az%7" +
                            "B%7C%7D~%7F%C2%80%C2%81%C3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "password",
                href = "http://example.net",
                newValue = "%c3%89t\u00e9",
                expected = mapOf("href" to "http://:%c3%89t%C3%A9@example.net/", "password" to "%c3%89t%C3%A9"),
            ),
            SetterCase(
                component = "password",
                href = "sc:///",
                newValue = "x",
                expected = mapOf("href" to "sc:///", "password" to ""),
            ),
            SetterCase(
                component = "password",
                href = "javascript://x/",
                newValue = "bowser",
                expected = mapOf("href" to "javascript://:bowser@x/", "password" to "bowser"),
            ),
            SetterCase(
                component = "password",
                href = "file://test/",
                newValue = "test",
                expected = mapOf("href" to "file://test/", "password" to ""),
            ),
            SetterCase(
                component = "pathname",
                href = "mailto:me@example.net",
                newValue = "/foo",
                expected = mapOf("href" to "mailto:me@example.net", "pathname" to "me@example.net"),
            ),
            SetterCase(
                component = "pathname",
                href = "data:original",
                newValue = "new value",
                expected = mapOf("href" to "data:original", "pathname" to "original"),
            ),
            SetterCase(
                component = "pathname",
                href = "sc:original",
                newValue = "new value",
                expected = mapOf("href" to "sc:original", "pathname" to "original"),
            ),
            SetterCase(
                component = "pathname",
                href = "file:///some/path",
                newValue = "",
                expected = mapOf("href" to "file:///", "pathname" to "/"),
            ),
            SetterCase(
                component = "pathname",
                href = "foo://somehost/some/path",
                newValue = "",
                expected = mapOf("href" to "foo://somehost", "pathname" to ""),
            ),
            SetterCase(
                component = "pathname",
                href = "foo:///some/path",
                newValue = "",
                expected = mapOf("href" to "foo://", "pathname" to ""),
            ),
            SetterCase(
                component = "pathname",
                href = "foo:/some/path",
                newValue = "",
                expected = mapOf("href" to "foo:/", "pathname" to "/"),
            ),
            SetterCase(
                component = "pathname",
                href = "foo:/some/path",
                newValue = "test",
                expected = mapOf("href" to "foo:/test", "pathname" to "/test"),
            ),
            SetterCase(
                component = "pathname",
                href = "unix:/run/foo.socket?timeout=10",
                newValue = "/var/log/../run/bar.socket",
                expected = mapOf("href" to "unix:/var/run/bar.socket?timeout=10", "pathname" to "/var/run/bar.socket"),
            ),
            SetterCase(
                component = "pathname",
                href = "https://example.net#nav",
                newValue = "home",
                expected = mapOf("href" to "https://example.net/home#nav", "pathname" to "/home"),
            ),
            SetterCase(
                component = "pathname",
                href = "https://example.net#nav",
                newValue = "../home",
                expected = mapOf("href" to "https://example.net/home#nav", "pathname" to "/home"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net/home?lang=fr#nav",
                newValue = "\\a\\%2E\\b\\%2e.\\c",
                expected = mapOf("href" to "http://example.net/a/c?lang=fr#nav", "pathname" to "/a/c"),
            ),
            SetterCase(
                component = "pathname",
                href = "view-source+http://example.net/home?lang=fr#nav",
                newValue = "\\a\\%2E\\b\\%2e.\\c",
                expected =
                    mapOf(
                        "href" to "view-source+http://example.net/\\a\\%2E\\b\\%2e.\\c?lang=fr#nav",
                        "pathname" to "/\\a\\%2E\\b\\%2e.\\c",
                    ),
            ),
            SetterCase(
                component = "pathname",
                href = "a:/",
                newValue =
                    "\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "href" to
                            "a:/%00%01%1F%20!%22%23\$%&'()*+,-./09:;%3C=%3E%3F@AZ[\\]%5E_%60az%7B|%7D~%7F%C2%80%C2%81" +
                            "%C3%89%C3%A9",
                        "pathname" to
                            "/%00%01%1F%20!%22%23\$%&'()*+,-./09:;%3C=%3E%3F@AZ[\\]%5E_%60az%7B|%7D~%7F%C2%80%C2%81%C" +
                            "3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "%2e%2E%c3%89t\u00e9",
                expected =
                    mapOf(
                        "href" to "http://example.net/%2e%2E%c3%89t%C3%A9",
                        "pathname" to "/%2e%2E%c3%89t%C3%A9",
                    ),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "?",
                expected = mapOf("href" to "http://example.net/%3F", "pathname" to "/%3F"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "#",
                expected = mapOf("href" to "http://example.net/%23", "pathname" to "/%23"),
            ),
            SetterCase(
                component = "pathname",
                href = "sc://example.net",
                newValue = "?",
                expected = mapOf("href" to "sc://example.net/%3F", "pathname" to "/%3F"),
            ),
            SetterCase(
                component = "pathname",
                href = "sc://example.net",
                newValue = "#",
                expected = mapOf("href" to "sc://example.net/%23", "pathname" to "/%23"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "/?\u00e9",
                expected = mapOf("href" to "http://example.net/%3F%C3%A9", "pathname" to "/%3F%C3%A9"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "/#\u00e9",
                expected = mapOf("href" to "http://example.net/%23%C3%A9", "pathname" to "/%23%C3%A9"),
            ),
            SetterCase(
                component = "pathname",
                href = "file://monkey/",
                newValue = "\\\\",
                expected = mapOf("href" to "file://monkey//", "pathname" to "//"),
            ),
            SetterCase(
                component = "pathname",
                href = "file:///unicorn",
                newValue = "//\\/",
                expected = mapOf("href" to "file://////", "pathname" to "////"),
            ),
            SetterCase(
                component = "pathname",
                href = "file:///unicorn",
                newValue = "//monkey/..//",
                expected = mapOf("href" to "file://///", "pathname" to "///"),
            ),
            SetterCase(
                component = "pathname",
                href = "non-spec:/",
                newValue = "/.//p",
                expected = mapOf("href" to "non-spec:/.//p", "pathname" to "//p"),
            ),
            SetterCase(
                component = "pathname",
                href = "non-spec:/",
                newValue = "/..//p",
                expected = mapOf("href" to "non-spec:/.//p", "pathname" to "//p"),
            ),
        )

    private fun part3(): List<SetterCase> =
        listOf(
            SetterCase(
                component = "pathname",
                href = "non-spec:/",
                newValue = "//p",
                expected = mapOf("href" to "non-spec:/.//p", "pathname" to "//p"),
            ),
            SetterCase(
                component = "pathname",
                href = "non-spec:/.//",
                newValue = "p",
                expected = mapOf("href" to "non-spec:/p", "pathname" to "/p"),
            ),
            SetterCase(
                component = "pathname",
                href = "data:/nospace",
                newValue = "space ",
                expected = mapOf("href" to "data:/space%20", "pathname" to "/space%20"),
            ),
            SetterCase(
                component = "pathname",
                href = "sc:/nospace",
                newValue = "space ",
                expected = mapOf("href" to "sc:/space%20", "pathname" to "/space%20"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = " ",
                expected = mapOf("href" to "http://example.net/%20", "pathname" to "/%20"),
            ),
            SetterCase(
                component = "pathname",
                href = "http://example.net",
                newValue = "\u0000",
                expected = mapOf("href" to "http://example.net/%00", "pathname" to "/%00"),
            ),
            SetterCase(
                component = "pathname",
                href = "foo://path/to",
                newValue = "/..",
                expected = mapOf("href" to "foo://path/", "pathname" to "/"),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net",
                newValue = "8080",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net:8080",
                newValue = "",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "http://example.net/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net:8080",
                newValue = "80",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "http://example.net/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "https://example.net:4433",
                newValue = "443",
                expected =
                    mapOf(
                        "host" to "example.net",
                        "hostname" to "example.net",
                        "href" to "https://example.net/",
                        "port" to "",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "https://example.net",
                newValue = "80",
                expected =
                    mapOf(
                        "host" to "example.net:80",
                        "hostname" to "example.net",
                        "href" to "https://example.net:80/",
                        "port" to "80",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080/stuff",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080?stuff",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080#stuff",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080\\stuff",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "view-source+http://example.net/path",
                newValue = "8080stuff2",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "view-source+http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080stuff2",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "8080+2",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net/path",
                newValue = "65535",
                expected =
                    mapOf(
                        "host" to "example.net:65535",
                        "hostname" to "example.net",
                        "href" to "http://example.net:65535/path",
                        "port" to "65535",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net:8080/path",
                newValue = "65536",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "http://example.net:8080/path",
                newValue = "randomstring",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "http://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "non-special://example.net:8080/path",
                newValue = "65536",
                expected =
                    mapOf(
                        "host" to "example.net:8080",
                        "hostname" to "example.net",
                        "href" to "non-special://example.net:8080/path",
                        "port" to "8080",
                    ),
            ),
            SetterCase(
                component = "port",
                href = "file://test/",
                newValue = "12",
                expected = mapOf("href" to "file://test/", "port" to ""),
            ),
            SetterCase(
                component = "port",
                href = "file://localhost/",
                newValue = "12",
                expected = mapOf("href" to "file:///", "port" to ""),
            ),
            SetterCase(
                component = "port",
                href = "non-base:value",
                newValue = "12",
                expected = mapOf("href" to "non-base:value", "port" to ""),
            ),
            SetterCase(
                component = "port",
                href = "sc:///",
                newValue = "12",
                expected = mapOf("href" to "sc:///", "port" to ""),
            ),
            SetterCase(
                component = "port",
                href = "sc://x/",
                newValue = "12",
                expected = mapOf("href" to "sc://x:12/", "port" to "12"),
            ),
            SetterCase(
                component = "port",
                href = "javascript://x/",
                newValue = "12",
                expected = mapOf("href" to "javascript://x:12/", "port" to "12"),
            ),
            SetterCase(
                component = "port",
                href = "https://domain.com:443",
                newValue = "\u00098080",
                expected = mapOf("port" to "8080"),
            ),
            SetterCase(
                component = "port",
                href = "wpt++://domain.com:443",
                newValue = "\u00098080",
                expected = mapOf("port" to "8080"),
            ),
            SetterCase(
                component = "port",
                href = "https://www.google.com:4343",
                newValue = "4wpt",
                expected = mapOf("port" to "4"),
            ),
            SetterCase(
                component = "port",
                href = "https://domain.com:3000",
                newValue = "\u000a\u000980\u000a\u000980\u000a\u0009",
                expected = mapOf("port" to "8080"),
            ),
            SetterCase(
                component = "port",
                href = "https://domain.com:3000",
                newValue = "\u000a\u000a\u0009\u0009",
                expected = mapOf("port" to "3000"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "b",
                expected = mapOf("href" to "b://example.net", "protocol" to "b:"),
            ),
            SetterCase(
                component = "protocol",
                href = "javascript:alert(1)",
                newValue = "defuse",
                expected = mapOf("href" to "defuse:alert(1)", "protocol" to "defuse:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "B",
                expected = mapOf("href" to "b://example.net", "protocol" to "b:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "\u00e9",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "0b",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "+b",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "bC0+-.",
                expected = mapOf("href" to "bc0+-.://example.net", "protocol" to "bc0+-.:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "b,c",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "a://example.net",
                newValue = "b\u00e9",
                expected = mapOf("href" to "a://example.net", "protocol" to "a:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test@example.net",
                newValue = "file",
                expected = mapOf("href" to "http://test@example.net/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "protocol",
                href = "https://example.net:1234",
                newValue = "file",
                expected = mapOf("href" to "https://example.net:1234/", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "wss://x:x@example.net:1234",
                newValue = "file",
                expected = mapOf("href" to "wss://x:x@example.net:1234/", "protocol" to "wss:"),
            ),
            SetterCase(
                component = "protocol",
                href = "file://localhost/",
                newValue = "http",
                expected = mapOf("href" to "file:///", "protocol" to "file:"),
            ),
            SetterCase(
                component = "protocol",
                href = "file:///test",
                newValue = "https",
                expected = mapOf("href" to "file:///test", "protocol" to "file:"),
            ),
            SetterCase(
                component = "protocol",
                href = "file:",
                newValue = "wss",
                expected = mapOf("href" to "file:///", "protocol" to "file:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://example.net",
                newValue = "b",
                expected = mapOf("href" to "http://example.net/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "protocol",
                href = "file://hi/path",
                newValue = "s",
                expected = mapOf("href" to "file://hi/path", "protocol" to "file:"),
            ),
            SetterCase(
                component = "protocol",
                href = "https://example.net",
                newValue = "s",
                expected = mapOf("href" to "https://example.net/", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "ftp://example.net",
                newValue = "test",
                expected = mapOf("href" to "ftp://example.net/", "protocol" to "ftp:"),
            ),
            SetterCase(
                component = "protocol",
                href = "mailto:me@example.net",
                newValue = "http",
                expected = mapOf("href" to "mailto:me@example.net", "protocol" to "mailto:"),
            ),
            SetterCase(
                component = "protocol",
                href = "ssh://me@example.net",
                newValue = "http",
                expected = mapOf("href" to "ssh://me@example.net", "protocol" to "ssh:"),
            ),
            SetterCase(
                component = "protocol",
                href = "ssh://me@example.net",
                newValue = "https",
                expected = mapOf("href" to "ssh://me@example.net", "protocol" to "ssh:"),
            ),
            SetterCase(
                component = "protocol",
                href = "ssh://me@example.net",
                newValue = "file",
                expected = mapOf("href" to "ssh://me@example.net", "protocol" to "ssh:"),
            ),
            SetterCase(
                component = "protocol",
                href = "ssh://example.net",
                newValue = "file",
                expected = mapOf("href" to "ssh://example.net", "protocol" to "ssh:"),
            ),
            SetterCase(
                component = "protocol",
                href = "nonsense:///test",
                newValue = "https",
                expected = mapOf("href" to "nonsense:///test", "protocol" to "nonsense:"),
            ),
        )

    private fun part4(): List<SetterCase> =
        listOf(
            SetterCase(
                component = "protocol",
                href = "http://example.net",
                newValue = "https:foo : bar",
                expected = mapOf("href" to "https://example.net/", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "data:text/html,<p>Test",
                newValue = "view-source+data:foo : bar",
                expected = mapOf("href" to "view-source+data:text/html,<p>Test", "protocol" to "view-source+data:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://foo.com:443/",
                newValue = "https",
                expected = mapOf("href" to "https://foo.com/", "port" to "", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "h\u000d\u000att\u0009ps",
                expected = mapOf("href" to "https://test/", "port" to "", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "https\u000d",
                expected = mapOf("href" to "https://test/", "protocol" to "https:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "https\u0000",
                expected = mapOf("href" to "http://test/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "https\u000c",
                expected = mapOf("href" to "http://test/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "https\u000e",
                expected = mapOf("href" to "http://test/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "protocol",
                href = "http://test/",
                newValue = "https ",
                expected = mapOf("href" to "http://test/", "protocol" to "http:"),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net#nav",
                newValue = "lang=fr",
                expected = mapOf("href" to "https://example.net/?lang=fr#nav", "search" to "?lang=fr"),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US#nav",
                newValue = "lang=fr",
                expected = mapOf("href" to "https://example.net/?lang=fr#nav", "search" to "?lang=fr"),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US#nav",
                newValue = "?lang=fr",
                expected = mapOf("href" to "https://example.net/?lang=fr#nav", "search" to "?lang=fr"),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US#nav",
                newValue = "??lang=fr",
                expected = mapOf("href" to "https://example.net/??lang=fr#nav", "search" to "??lang=fr"),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US#nav",
                newValue = "?",
                expected = mapOf("href" to "https://example.net/?#nav", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US#nav",
                newValue = "",
                expected = mapOf("href" to "https://example.net/#nav", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net?lang=en-US",
                newValue = "",
                expected = mapOf("href" to "https://example.net/", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "https://example.net",
                newValue = "",
                expected = mapOf("href" to "https://example.net/", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "a:/",
                newValue =
                    "\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "href" to
                            "a:/?%00%01%1F%20!%22%23\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_`az{|}~%7F%C2%80%C2%81%C3%89%C3" +
                            "%A9",
                        "search" to
                            "?%00%01%1F%20!%22%23\$%&'()*+,-./09:;%3C=%3E?@AZ[\\]^_`az{|}~%7F%C2%80%C2%81%C3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "search",
                href = "http://example.net",
                newValue = "%c3%89t\u00e9",
                expected = mapOf("href" to "http://example.net/?%c3%89t%C3%A9", "search" to "?%c3%89t%C3%A9"),
            ),
            SetterCase(
                component = "search",
                href = "data:space ?query",
                newValue = "",
                expected = mapOf("href" to "data:space%20", "pathname" to "space%20", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "sc:space ?query",
                newValue = "",
                expected = mapOf("href" to "sc:space%20", "pathname" to "space%20", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "data:space  ?query#fragment",
                newValue = "",
                expected = mapOf("href" to "data:space %20#fragment", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "sc:space  ?query#fragment",
                newValue = "",
                expected = mapOf("href" to "sc:space %20#fragment", "search" to ""),
            ),
            SetterCase(
                component = "search",
                href = "http://example.net",
                newValue = " ",
                expected = mapOf("href" to "http://example.net/?%20", "search" to "?%20"),
            ),
            SetterCase(
                component = "search",
                href = "http://example.net",
                newValue = "\u0000",
                expected = mapOf("href" to "http://example.net/?%00", "search" to "?%00"),
            ),
            SetterCase(
                component = "username",
                href = "file:///home/you/index.html",
                newValue = "me",
                expected = mapOf("href" to "file:///home/you/index.html", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "unix:/run/foo.socket",
                newValue = "me",
                expected = mapOf("href" to "unix:/run/foo.socket", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "mailto:you@example.net",
                newValue = "me",
                expected = mapOf("href" to "mailto:you@example.net", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "javascript:alert(1)",
                newValue = "wario",
                expected = mapOf("href" to "javascript:alert(1)", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "http://example.net",
                newValue = "me",
                expected = mapOf("href" to "http://me@example.net/", "username" to "me"),
            ),
            SetterCase(
                component = "username",
                href = "http://:secret@example.net",
                newValue = "me",
                expected = mapOf("href" to "http://me:secret@example.net/", "username" to "me"),
            ),
            SetterCase(
                component = "username",
                href = "http://me@example.net",
                newValue = "",
                expected = mapOf("href" to "http://example.net/", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "http://me:secret@example.net",
                newValue = "",
                expected = mapOf("href" to "http://:secret@example.net/", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "http://example.net",
                newValue =
                    "\u0000\u0001\u0009\u000a\u000d\u001f !\"#\$%&'()*+,-./09:;<=>?@AZ[\\]^_`az{|}~\u007f\u0080" +
                        "\u0081\u00c9\u00e9",
                expected =
                    mapOf(
                        "href" to
                            "http://%00%01%09%0A%0D%1F%20!%22%23\$%&'()*+,-.%2F09%3A%3B%3C%3D%3E%3F%40AZ%5B%5C%5D%5E_" +
                            "%60az%7B%7C%7D~%7F%C2%80%C2%81%C3%89%C3%A9@example.net/",
                        "username" to
                            "%00%01%09%0A%0D%1F%20!%22%23\$%&'()*+,-.%2F09%3A%3B%3C%3D%3E%3F%40AZ%5B%5C%5D%5E_%60az%7" +
                            "B%7C%7D~%7F%C2%80%C2%81%C3%89%C3%A9",
                    ),
            ),
            SetterCase(
                component = "username",
                href = "http://example.net",
                newValue = "%c3%89t\u00e9",
                expected = mapOf("href" to "http://%c3%89t%C3%A9@example.net/", "username" to "%c3%89t%C3%A9"),
            ),
            SetterCase(
                component = "username",
                href = "sc:///",
                newValue = "x",
                expected = mapOf("href" to "sc:///", "username" to ""),
            ),
            SetterCase(
                component = "username",
                href = "javascript://x/",
                newValue = "wario",
                expected = mapOf("href" to "javascript://wario@x/", "username" to "wario"),
            ),
            SetterCase(
                component = "username",
                href = "file://test/",
                newValue = "test",
                expected = mapOf("href" to "file://test/", "username" to ""),
            ),
        )
}

/** Every WPT `setters_tests.json` case, flattened across components. */
internal val SETTER_TEST_CASES: List<SetterCase> = SetterCaseData.all()
