// Copyright (c) 2026 dexpace and Omar Aljarrah
// SPDX-License-Identifier: MIT

// The percent-encoding generator reads the vendored WPT percent-encoding.json corpus and
// materializes the Kotlin PercentEncodingTestData fixture. Each corpus entry pins one
// percent-encoding expectation across several charsets; only the utf-8 expectation is emitted,
// since UTF-8 is kuri's sole charset. Like setters.go, entries carry no lone-surrogate inputs,
// so cases decode straight into Go strings rather than through url.go's lossless UTF-16 path.
package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf16"
)

// percentChunkSize is the number of cases per generated builder method, kept well under the
// 64 KB JVM method limit so no single method overflows.
const percentChunkSize = 60

// percentCase is one in-scope corpus entry: percent-encoding input under the C0-control set
// over UTF-8 bytes must equal utf8.
type percentCase struct {
	input string
	utf8  string
}

// percentEntry mirrors one array element of percent-encoding.json: {input, output: {utf-8, ...}}.
// Charsets other than utf-8 (big5, shift_jis, ...) are intentionally not modelled; kuri is
// UTF-8-only, so a case whose only expectations are non-UTF-8 charsets is out of scope.
type percentEntry struct {
	Input  *string           `json:"input"`
	Output map[string]string `json:"output"`
}

// percentInputPath returns the absolute path of the vendored WPT corpus.
func percentInputPath() (string, error) {
	root, err := Root()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, ".claude", "references", "ada", "tests", "wpt", "percent-encoding.json"), nil
}

// generatePercentEncoding reads the corpus and returns the complete Kotlin source string.
func generatePercentEncoding() (string, error) {
	path, err := percentInputPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	cases, err := percentLoadCases(data)
	if err != nil {
		return "", err
	}
	return percentEmitFixture(cases), nil
}

// percentLoadCases decodes the top-level JSON array and keeps only objects carrying both an
// `input` key and a `utf-8` output expectation, preserving document order with no sorting or
// deduplication. Documentation strings (skipped via firstNonSpace, as url.go does) and objects
// lacking a utf-8 expectation are dropped.
func percentLoadCases(data []byte) ([]percentCase, error) {
	var elements []json.RawMessage
	if err := json.Unmarshal(data, &elements); err != nil {
		return nil, fmt.Errorf("percent-encoding: decoding corpus array: %w", err)
	}
	cases := make([]percentCase, 0, len(elements))
	for index, element := range elements {
		if firstNonSpace(element) != '{' {
			continue // documentation string
		}
		var entry percentEntry
		if err := json.Unmarshal(element, &entry); err != nil {
			return nil, fmt.Errorf("percent-encoding: decoding object at index %d: %w", index, err)
		}
		if entry.Input == nil {
			continue
		}
		utf8, ok := entry.Output["utf-8"]
		if !ok {
			fmt.Fprintf(os.Stderr, "percent-encoding: skipping entry %q (no utf-8 output)\n", *entry.Input)
			continue // only UTF-8 is in scope
		}
		cases = append(cases, percentCase{input: *entry.Input, utf8: utf8})
	}
	return cases, nil
}

// percentEmitFixture renders the complete fixture: license header, suppress block, package,
// data class, and the chunked builder object, terminated by exactly one newline. The structure
// mirrors urlEmitFixture and settersEmitFixture.
func percentEmitFixture(cases []percentCase) string {
	parts := Chunk(cases, percentChunkSize)
	lines := []string{LicenseHeader, ""}
	lines = append(lines, FileSuppressBlock(bulkDataComments, "LongMethod", "LargeClass", "MatchingDeclarationName")...)
	lines = append(lines,
		"package org.dexpace.kuri.percent",
		"",
	)
	lines = append(lines, percentDataClassLines()...)
	lines = append(lines,
		"",
		"// Generated by ./gradlew generatePercentEncodingTestData from the WPT percent-encoding corpus.",
		"// Chunked into small builders so no single method exceeds the 64 KB JVM limit.",
		"private object PercentEncodingCaseData {",
	)
	lines = append(lines, allAccessorLines(parts)...)
	for index, part := range parts {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("    private fun part%d(): List<PercentEncodingCase> =", index))
		lines = append(lines, "        listOf(")
		for _, current := range part {
			lines = append(lines, percentCaseLines(current)...)
		}
		lines = append(lines, "        )")
	}
	lines = append(lines,
		"}",
		"",
		"/** Every WPT `percent-encoding.json` case carrying a `utf-8` expectation. */",
		"internal val PERCENT_ENCODING_TEST_CASES: List<PercentEncodingCase> = PercentEncodingCaseData.all()",
	)
	return JoinLines(lines)
}

// allAccessorLines renders the `fun all(): List<PercentEncodingCase> = ...` accessor. With a
// single chunk (the whole corpus is a handful of cases, unlike url.go's/setters.go's larger
// corpora) PartSumExpression collapses to one term, `part0()`, and ktlint's function-signature
// rule then requires that single-line body to join the signature rather than wrap to its own
// line; with more than one chunk the body spans multiple lines and must wrap regardless.
func allAccessorLines(parts [][]percentCase) []string {
	signature := "    fun all(): List<PercentEncodingCase> ="
	body := PartSumExpression(len(parts))
	if !strings.Contains(body, "\n") {
		combined := signature + " " + body
		if len(combined) <= MaxCols {
			return []string{combined}
		}
	}
	return []string{signature, "        " + body}
}

// percentCaseLines renders one PercentEncodingCase constructor call as indented named
// arguments, reusing FieldLines so an unusually long input/utf8 pair wraps the same way
// url.go's UrlCase fields do.
func percentCaseLines(c percentCase) []string {
	lines := []string{"            PercentEncodingCase("}
	lines = append(lines, FieldLines("input", utf16.Encode([]rune(c.input)), fieldIndent)...)
	lines = append(lines, FieldLines("utf8", utf16.Encode([]rune(c.utf8)), fieldIndent)...)
	lines = append(lines, "            ),")
	return lines
}

// percentDataClassLines is the fixed KDoc + PercentEncodingCase data-class declaration.
func percentDataClassLines() []string {
	return []string{
		"/**",
		" * One WPT `percent-encoding.json` case carrying a `utf-8` expectation (the only charset in",
		" * scope for kuri). Percent-encoding [input] under the C0-control set over UTF-8 bytes must",
		" * equal [utf8].",
		" */",
		"internal data class PercentEncodingCase(",
		"    val input: String,",
		"    val utf8: String,",
		")",
	}
}
