// Copyright (c) 2026 dexpace and Omar Aljarrah
// SPDX-License-Identifier: MIT

// The setters generator reads the vendored WPT setters_tests.json corpus and
// materializes the Kotlin SetterTestData fixture. Each corpus entry pins one URL
// setter invocation: parse `href`, assign `newValue` through the named component
// setter, then assert every getter listed in `expected` afterward. Unlike
// urltestdata.json, this corpus carries no lone-surrogate inputs, so cases decode
// straight into Go strings rather than through the lossless UTF-16 path url.go
// needs; the values still round-trip through UTF-16 code units when a line needs
// wrapping, reusing the same column-aware helpers.
package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf16"
)

// settersChunkSize is the number of cases per generated builder method, kept well
// under the 64 KB JVM method limit so no single method overflows.
const settersChunkSize = 60

// setterCase is one in-scope corpus entry: assigning newValue through component's
// setter on the URL parsed from href must leave every getter named in expected
// equal to its mapped string. expected is unordered — the Task 10 assertion
// checks each entry independently, so key order carries no meaning here.
type setterCase struct {
	component string
	href      string
	newValue  string
	expected  map[string]string
}

// setterEntry mirrors one array element of setters_tests.json: {href, new_value,
// expected}. comment is intentionally not modelled; it is documentation only and
// never reaches the generated fixture.
type setterEntry struct {
	Href     string            `json:"href"`
	NewValue string            `json:"new_value"`
	Expected map[string]string `json:"expected"`
}

// settersInputPath returns the absolute path of the vendored WPT corpus.
func settersInputPath() (string, error) {
	root, err := Root()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, ".claude", "references", "ada", "tests", "wpt", "setters_tests.json"), nil
}

// generateSetters reads the corpus and returns the complete Kotlin source string.
func generateSetters() (string, error) {
	path, err := settersInputPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	cases, err := settersLoadCases(data)
	if err != nil {
		return "", err
	}
	return settersEmitFixture(cases), nil
}

// settersLoadCases decodes the top-level JSON object and flattens it into one
// case list. The object's keys are component names (`protocol`, ..., `href`)
// plus a documentation-only `comment` key, which is skipped; components are
// visited in sorted order for deterministic output, while each component's
// entries keep their original corpus order (no sort, no dedup).
func settersLoadCases(data []byte) ([]setterCase, error) {
	var byComponent map[string]json.RawMessage
	if err := json.Unmarshal(data, &byComponent); err != nil {
		return nil, fmt.Errorf("setters: decoding corpus object: %w", err)
	}
	components := make([]string, 0, len(byComponent))
	for name := range byComponent {
		if name == "comment" {
			continue
		}
		components = append(components, name)
	}
	sort.Strings(components)
	var cases []setterCase
	for _, name := range components {
		var entries []setterEntry
		if err := json.Unmarshal(byComponent[name], &entries); err != nil {
			return nil, fmt.Errorf("setters: decoding %s entries: %w", name, err)
		}
		for index, entry := range entries {
			if entry.Expected == nil {
				return nil, fmt.Errorf("setters: %s entry %d has no expected object", name, index)
			}
			cases = append(cases, setterCase{
				component: name,
				href:      entry.Href,
				newValue:  entry.NewValue,
				expected:  entry.Expected,
			})
		}
	}
	return cases, nil
}

// settersEmitFixture renders the complete fixture: license header, suppress
// block, package, data class, and the chunked builder object, terminated by
// exactly one newline. The structure mirrors urlEmitFixture.
func settersEmitFixture(cases []setterCase) string {
	parts := Chunk(cases, settersChunkSize)
	lines := []string{LicenseHeader, ""}
	lines = append(lines, FileSuppressBlock(bulkDataComments, "LongMethod", "LargeClass", "MatchingDeclarationName")...)
	lines = append(lines,
		"package org.dexpace.kuri.parser",
		"",
	)
	lines = append(lines, settersDataClassLines()...)
	lines = append(lines,
		"",
		"// Generated by ./gradlew generateSetterTestData from the WPT setters_tests corpus.",
		"// Chunked into small builders so no single method exceeds the 64 KB JVM limit.",
		"private object SetterCaseData {",
	)
	lines = append(lines, "    fun all(): List<SetterCase> =")
	lines = append(lines, "        "+PartSumExpression(len(parts)))
	for index, part := range parts {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("    private fun part%d(): List<SetterCase> =", index))
		lines = append(lines, "        listOf(")
		for _, current := range part {
			lines = append(lines, setterCaseLines(current)...)
		}
		lines = append(lines, "        )")
	}
	lines = append(lines,
		"}",
		"",
		"/** Every WPT `setters_tests.json` case, flattened across components. */",
		"internal val SETTER_TEST_CASES: List<SetterCase> = SetterCaseData.all()",
	)
	return JoinLines(lines)
}

// setterCaseLines renders one SetterCase constructor call as indented named
// arguments, reusing FieldLines for the three string fields so an unusually
// long href/newValue (the corpus has entries whose escaped form exceeds 100
// columns) wraps the same way url.go's UrlCase fields do.
func setterCaseLines(c setterCase) []string {
	lines := []string{"            SetterCase("}
	lines = append(lines, FieldLines("component", utf16.Encode([]rune(c.component)), fieldIndent)...)
	lines = append(lines, FieldLines("href", utf16.Encode([]rune(c.href)), fieldIndent)...)
	lines = append(lines, FieldLines("newValue", utf16.Encode([]rune(c.newValue)), fieldIndent)...)
	lines = append(lines, expectedFieldLines(c.expected, fieldIndent)...)
	lines = append(lines, "            ),")
	return lines
}

// expectedFieldLines renders the `expected = mapOf(...)` field, keys sorted for
// deterministic output. The whole map collapses onto one line when it fits
// within MaxCols (the common case: most entries carry one or two getters);
// otherwise it wraps to one key per line via expectedEntryLines, which itself
// wraps an individual over-long value (the corpus has `expected` values whose
// escaped form alone exceeds 120 columns).
func expectedFieldLines(expected map[string]string, indent int) []string {
	keys := make([]string, 0, len(expected))
	for key := range expected {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	pad := strings.Repeat(" ", indent)
	pairs := make([]string, len(keys))
	for i, key := range keys {
		pairs[i] = KotlinString(key) + " to " + KotlinString(expected[key])
	}
	single := pad + "expected = mapOf(" + strings.Join(pairs, ", ") + "),"
	if len(single) <= MaxCols {
		return []string{single}
	}
	// ktlint requires a multiline call on the right of an `=` to start on its own
	// line, so "mapOf(" cannot trail "expected =" on the same line here.
	mapPad := strings.Repeat(" ", indent+4)
	lines := []string{pad + "expected =", mapPad + "mapOf("}
	for _, key := range keys {
		lines = append(lines, expectedEntryLines(key, expected[key], indent+8)...)
	}
	lines = append(lines, mapPad+"),")
	return lines
}

// expectedEntryLines renders one `"key" to "value",` line inside a wrapped
// mapOf(...) call. When even that single line would exceed MaxCols, the value
// itself wraps across `"..." +` continuation segments at a single continuation
// indent (unlike FieldLinesIndented's two-tier first/rest split), matching what
// ktlint accepts for a continuation nested this deep inside a `to` infix call.
func expectedEntryLines(key, value string, indent int) []string {
	pad := strings.Repeat(" ", indent)
	single := pad + KotlinString(key) + " to " + KotlinString(value) + ","
	if len(single) <= MaxCols {
		return []string{single}
	}
	units := utf16.Encode([]rune(value))
	contIndent := indent + 4
	budget := MaxCols - contIndent - len(" +")
	segments := packSegments(EscapeTokensUTF16(units), budget)
	contPad := strings.Repeat(" ", contIndent)
	lines := make([]string, 0, len(segments)+1)
	lines = append(lines, pad+KotlinString(key)+" to")
	for index, segment := range segments {
		tail := " +"
		if index == len(segments)-1 {
			tail = ","
		}
		lines = append(lines, contPad+`"`+segment+`"`+tail)
	}
	return lines
}

// settersDataClassLines is the fixed KDoc + SetterCase data-class declaration.
func settersDataClassLines() []string {
	return []string{
		"/**",
		" * One WPT `setters_tests.json` case. Assigning [newValue] through the [component] setter on",
		" * the URL parsed from [href] must leave every getter named in [expected] (keyed by getter name,",
		" * e.g. `href`, `protocol`, `hostname`) equal to its mapped string; [expected] is unordered.",
		" */",
		"internal data class SetterCase(",
		"    val component: String,",
		"    val href: String,",
		"    val newValue: String,",
		"    val expected: Map<String, String>,",
		")",
	}
}
