// Copyright (c) 2026 dexpace and Omar Aljarrah
// SPDX-License-Identifier: MIT

// The urlencoded generator reads the vendored WPT urlencoded-parser corpus and materializes the
// Kotlin UrlEncodedTestData fixture. There is no standalone JSON resource upstream: the corpus is
// hand-extracted from the array literal at the top of WPT's url/urlencoded-parser.any.js. Only the
// plain input/output pairs feeding that file's "URLSearchParams constructed with" subtest are
// vendored; its two sibling formData() subtests exercise non-UTF-8 charsets (windows-1252,
// shift_jis) that are out of scope, since kuri's form codec is UTF-8-only. Like percentencoding.go,
// no entry carries a lone surrogate, so decoding goes straight through encoding/json rather than
// url.go's/json.go's UTF-16 lossless path.
package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf16"
)

// urlEncodedChunkSize is the number of cases per generated builder method, kept well under the
// 64 KB JVM constant-pool limit so no single method overflows.
const urlEncodedChunkSize = 60

// urlEncodedPair is one decoded name/value pair of a case's expected output, in appearance order.
type urlEncodedPair struct {
	name  string
	value string
}

// urlEncodedCase is one in-scope corpus entry: parsing input as application/x-www-form-urlencoded
// must yield output, in order.
type urlEncodedCase struct {
	input  string
	output []urlEncodedPair
}

// urlEncodedEntry mirrors one array element of urlencoded-parser.json: {input, output: [[name,
// value], ...]}.
type urlEncodedEntry struct {
	Input  *string    `json:"input"`
	Output [][]string `json:"output"`
}

// urlEncodedInputPath returns the absolute path of the vendored WPT corpus.
func urlEncodedInputPath() (string, error) {
	root, err := Root()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "tools", "urlencoded", "urlencoded-parser.json"), nil
}

// generateUrlEncoded reads the corpus and returns the complete Kotlin source string.
func generateUrlEncoded() (string, error) {
	path, err := urlEncodedInputPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	cases, err := urlEncodedLoadCases(data)
	if err != nil {
		return "", err
	}
	return urlEncodedEmitFixture(cases)
}

// urlEncodedLoadCases decodes the top-level JSON array and keeps only objects carrying an `input`
// key, preserving document order with no sorting or deduplication. The leading documentation
// string (skipped via firstNonSpace, as url.go/percentencoding.go do) is dropped.
func urlEncodedLoadCases(data []byte) ([]urlEncodedCase, error) {
	var elements []json.RawMessage
	if err := json.Unmarshal(data, &elements); err != nil {
		return nil, fmt.Errorf("urlencoded: decoding corpus array: %w", err)
	}
	cases := make([]urlEncodedCase, 0, len(elements))
	for index, element := range elements {
		if firstNonSpace(element) != '{' {
			continue // documentation string
		}
		var entry urlEncodedEntry
		if err := json.Unmarshal(element, &entry); err != nil {
			return nil, fmt.Errorf("urlencoded: decoding object at index %d: %w", index, err)
		}
		if entry.Input == nil {
			continue
		}
		output, err := urlEncodedPairs(entry.Output, index)
		if err != nil {
			return nil, err
		}
		cases = append(cases, urlEncodedCase{input: *entry.Input, output: output})
	}
	return cases, nil
}

// urlEncodedPairs converts one entry's raw [[name, value], ...] rows into pairs, erroring on any
// row that is not exactly two elements (the shape every corpus row currently has).
func urlEncodedPairs(rows [][]string, index int) ([]urlEncodedPair, error) {
	pairs := make([]urlEncodedPair, 0, len(rows))
	for _, row := range rows {
		if len(row) != 2 {
			return nil, fmt.Errorf("urlencoded: entry %d has an output row with %d elements, want 2", index, len(row))
		}
		pairs = append(pairs, urlEncodedPair{name: row[0], value: row[1]})
	}
	return pairs, nil
}

// urlEncodedEmitFixture renders the complete fixture: license header, suppress block, package,
// data class, and the chunked builder object, terminated by exactly one newline. The structure
// mirrors urlEmitFixture/percentEmitFixture.
func urlEncodedEmitFixture(cases []urlEncodedCase) (string, error) {
	parts := Chunk(cases, urlEncodedChunkSize)
	lines := []string{LicenseHeader, ""}
	lines = append(lines, FileSuppressBlock(bulkDataComments, "LongMethod", "LargeClass", "MatchingDeclarationName")...)
	lines = append(lines,
		"package org.dexpace.kuri.query",
		"",
	)
	lines = append(lines, urlEncodedDataClassLines()...)
	lines = append(lines,
		"",
		"// Generated by ./gradlew generateUrlEncodedTestData from the WPT urlencoded-parser corpus.",
		"// Chunked into small builders so no single method exceeds the 64 KB JVM limit.",
		"private object UrlEncodedCaseData {",
	)
	lines = append(lines, urlEncodedAllAccessorLines(parts)...)
	for index, part := range parts {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("    private fun part%d(): List<UrlEncodedCase> =", index))
		lines = append(lines, "        listOf(")
		for _, current := range part {
			caseLines, err := urlEncodedCaseLines(current)
			if err != nil {
				return "", err
			}
			lines = append(lines, caseLines...)
		}
		lines = append(lines, "        )")
	}
	lines = append(lines,
		"}",
		"",
		"/** Every WPT `urlencoded-parser.json` case (objects carrying an `input`). */",
		"internal val URL_ENCODED_TEST_CASES: List<UrlEncodedCase> = UrlEncodedCaseData.all()",
	)
	return JoinLines(lines), nil
}

// urlEncodedAllAccessorLines renders the `fun all(): List<UrlEncodedCase> = ...` accessor,
// mirroring percentencoding.go's allAccessorLines: with a single chunk (the whole corpus is a
// handful of cases) PartSumExpression collapses to one term and, when the combined signature and
// body still fit MaxCols, ktlint's function-signature rule requires that single line rather than a
// wrap; with more than one chunk the body spans multiple lines and must wrap regardless.
func urlEncodedAllAccessorLines(parts [][]urlEncodedCase) []string {
	signature := "    fun all(): List<UrlEncodedCase> ="
	body := PartSumExpression(len(parts))
	if !strings.Contains(body, "\n") {
		combined := signature + " " + body
		if len(combined) <= MaxCols {
			return []string{combined}
		}
	}
	return []string{signature, "        " + body}
}

// urlEncodedCaseLines renders one UrlEncodedCase constructor call as indented named arguments.
func urlEncodedCaseLines(c urlEncodedCase) ([]string, error) {
	lines := []string{"            UrlEncodedCase("}
	lines = append(lines, FieldLines("input", utf16.Encode([]rune(c.input)), fieldIndent)...)
	outputLines, err := urlEncodedOutputLines(c.output)
	if err != nil {
		return nil, err
	}
	lines = append(lines, outputLines...)
	lines = append(lines, "            ),")
	return lines, nil
}

// urlEncodedOutputLines renders the `output = listOf("name" to "value", ...),` field (or
// `output = emptyList(),` when the case yields no pairs). ktlint requires a multiline call on the
// right of an `=` to start on its own line (as expectedFieldLines notes for `mapOf`), so `listOf(`
// cannot trail `output =` on the same line. Every corpus name/value is short enough that one pair
// fits one line comfortably within MaxCols; a pair that would not is a genuine generator gap, so it
// errors rather than silently emitting an over-long line for ktlint to catch.
func urlEncodedOutputLines(pairs []urlEncodedPair) ([]string, error) {
	pad := strings.Repeat(" ", fieldIndent)
	if len(pairs) == 0 {
		return []string{pad + "output = emptyList(),"}, nil
	}
	listPad := strings.Repeat(" ", fieldIndent+4)
	entryPad := strings.Repeat(" ", fieldIndent+8)
	lines := []string{pad + "output =", listPad + "listOf("}
	for _, pair := range pairs {
		line := entryPad + KotlinString(pair.name) + " to " + KotlinString(pair.value) + ","
		if len(line) > MaxCols {
			return nil, fmt.Errorf("urlencoded: output pair %q/%q exceeds %d columns", pair.name, pair.value, MaxCols)
		}
		lines = append(lines, line)
	}
	lines = append(lines, listPad+"),")
	return lines, nil
}

// urlEncodedDataClassLines is the fixed KDoc + UrlEncodedCase data-class declaration.
func urlEncodedDataClassLines() []string {
	return []string{
		"/**",
		" * One WPT `urlencoded-parser.json` case: parsing [input] as `application/x-www-form-urlencoded`",
		" * must yield [output], the ordered list of decoded `(name, value)` pairs.",
		" */",
		"internal data class UrlEncodedCase(",
		"    val input: String,",
		"    val output: List<Pair<String, String>>,",
		")",
	}
}
