/*
 * Copyright (c) 2026 dexpace and Omar Aljarrah
 * SPDX-License-Identifier: MIT
 */

// Generated bulk data, not hand-written logic: the chunked builders intentionally exceed
// detekt's method/class-size heuristics to stay within the 64 KB JVM method limit.
@file:Suppress("LongMethod", "LargeClass", "MatchingDeclarationName")

package org.dexpace.kuri.query

/**
 * One WPT `urlencoded-parser.json` case: parsing [input] as `application/x-www-form-urlencoded`
 * must yield [output], the ordered list of decoded `(name, value)` pairs.
 */
internal data class UrlEncodedCase(
    val input: String,
    val output: List<Pair<String, String>>,
)

// Generated by ./gradlew generateUrlEncodedTestData from the WPT urlencoded-parser corpus.
// Chunked into small builders so no single method exceeds the 64 KB JVM limit.
private object UrlEncodedCaseData {
    fun all(): List<UrlEncodedCase> = part0()

    private fun part0(): List<UrlEncodedCase> =
        listOf(
            UrlEncodedCase(
                input = "test",
                output =
                    listOf(
                        "test" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "\ufefftest=\ufeff",
                output =
                    listOf(
                        "\ufefftest" to "\ufeff",
                    ),
            ),
            UrlEncodedCase(
                input = "%EF%BB%BFtest=%EF%BB%BF",
                output =
                    listOf(
                        "\ufefftest" to "\ufeff",
                    ),
            ),
            UrlEncodedCase(
                input = "%EF%BF%BF=%EF%BF%BF",
                output =
                    listOf(
                        "\uffff" to "\uffff",
                    ),
            ),
            UrlEncodedCase(
                input = "%FE%FF",
                output =
                    listOf(
                        "\ufffd\ufffd" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "%FF%FE",
                output =
                    listOf(
                        "\ufffd\ufffd" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "\u2020&\u2020=x",
                output =
                    listOf(
                        "\u2020" to "",
                        "\u2020" to "x",
                    ),
            ),
            UrlEncodedCase(
                input = "%C2",
                output =
                    listOf(
                        "\ufffd" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "%C2x",
                output =
                    listOf(
                        "\ufffdx" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "_charset_=windows-1252&test=%C2x",
                output =
                    listOf(
                        "_charset_" to "windows-1252",
                        "test" to "\ufffdx",
                    ),
            ),
            UrlEncodedCase(
                input = "",
                output = emptyList(),
            ),
            UrlEncodedCase(
                input = "a",
                output =
                    listOf(
                        "a" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "a=b",
                output =
                    listOf(
                        "a" to "b",
                    ),
            ),
            UrlEncodedCase(
                input = "a=",
                output =
                    listOf(
                        "a" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "=b",
                output =
                    listOf(
                        "" to "b",
                    ),
            ),
            UrlEncodedCase(
                input = "&",
                output = emptyList(),
            ),
            UrlEncodedCase(
                input = "&a",
                output =
                    listOf(
                        "a" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "a&",
                output =
                    listOf(
                        "a" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "a&a",
                output =
                    listOf(
                        "a" to "",
                        "a" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "a&b&c",
                output =
                    listOf(
                        "a" to "",
                        "b" to "",
                        "c" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "a=b&c=d",
                output =
                    listOf(
                        "a" to "b",
                        "c" to "d",
                    ),
            ),
            UrlEncodedCase(
                input = "a=b&c=d&",
                output =
                    listOf(
                        "a" to "b",
                        "c" to "d",
                    ),
            ),
            UrlEncodedCase(
                input = "&&&a=b&&&&c=d&",
                output =
                    listOf(
                        "a" to "b",
                        "c" to "d",
                    ),
            ),
            UrlEncodedCase(
                input = "a=a&a=b&a=c",
                output =
                    listOf(
                        "a" to "a",
                        "a" to "b",
                        "a" to "c",
                    ),
            ),
            UrlEncodedCase(
                input = "a==a",
                output =
                    listOf(
                        "a" to "=a",
                    ),
            ),
            UrlEncodedCase(
                input = "a=a+b+c+d",
                output =
                    listOf(
                        "a" to "a b c d",
                    ),
            ),
            UrlEncodedCase(
                input = "%=a",
                output =
                    listOf(
                        "%" to "a",
                    ),
            ),
            UrlEncodedCase(
                input = "%a=a",
                output =
                    listOf(
                        "%a" to "a",
                    ),
            ),
            UrlEncodedCase(
                input = "%a_=a",
                output =
                    listOf(
                        "%a_" to "a",
                    ),
            ),
            UrlEncodedCase(
                input = "%61=a",
                output =
                    listOf(
                        "a" to "a",
                    ),
            ),
            UrlEncodedCase(
                input = "%61+%4d%4D=",
                output =
                    listOf(
                        "a MM" to "",
                    ),
            ),
            UrlEncodedCase(
                input = "id=0&value=%",
                output =
                    listOf(
                        "id" to "0",
                        "value" to "%",
                    ),
            ),
            UrlEncodedCase(
                input = "b=%2sf%2a",
                output =
                    listOf(
                        "b" to "%2sf*",
                    ),
            ),
            UrlEncodedCase(
                input = "b=%2%2af%2a",
                output =
                    listOf(
                        "b" to "%2*f*",
                    ),
            ),
            UrlEncodedCase(
                input = "b=%%2a",
                output =
                    listOf(
                        "b" to "%*",
                    ),
            ),
        )
}

/** Every WPT `urlencoded-parser.json` case (objects carrying an `input`). */
internal val URL_ENCODED_TEST_CASES: List<UrlEncodedCase> = UrlEncodedCaseData.all()
